### ISSUE TITLE
BatchInsert doesn't work with SQLite

### ISSUE THREAD

**Issue by Ygilany** [knex/knex#3561] opened 2019-12-04 18:54 UTC
# Environment

Knex version: 0.20.3
Database + version: Sqlite3 - npm package 4.1.0
OS: macOS

Select applicable template from below.
If issue is about oracledb support, tag @ atiertant. For MSSql tag @ smorey2.
Rest of dialects don't need tags.
If issue is about TypeScript definitions, tag @ lorefnon.

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

I'm not able to use batchInsert with Sqlite

2. Error message

Not getting an error. It times out. I'm using sqlite to run unit tests, and the tests are timing out everytime it reaches a batchInsert job. 

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

I was able to track it down to this line here 
https://github.com/knex/knex/blob/f56eaf5cfc7d24b27498f2e8ee645ea0e9515341/lib/util/batchInsert.js#L35

when I commented it out. everything just worked :)
it does however work on postgresql without an issue

**Comment by maximelkin** [comment] 2019-12-09 19:03
@Ygilany is this browser or node?

**Comment by elhigu** [comment] 2019-12-10 09:43
Please add full reproduction code for this. Closing until more info provided.

**Closed by elhigu** 2019-12-10 09:43 UTC

**Comment by Ygilany** [comment] 2019-12-10 14:58
This is node.
Lib function
```js
exports.bulkCreate = (races) => {
  return Bookshelf.knex.batchInsert(`races`, races);
};
```
route function:
```js
server.post(
    `race/bulk/new`, async (req, res) => {
      try {
        const races = await Race.bulkCreate(req.params.races);

        ResponseHandler(
          res,
          `Successfully created races`,
          { races }
        );
      } catch (err) {
        ErrorHandler(req, res, err);
      }
    }
  );
```
test with Jest
```js
it(`Bulk create races`, function() {
    return supertest(server)
      .post(`/race/bulk/new`)
      .send({
        races: [
          {name: `Test`}
        ]
      })
      .expect(200);
  });
```
The test times-out not matter what timeout setting I used. The same test works fine when running with other databases. so it's not an issue with jest.
```
    : Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:
```
also as I mentioned in the issue above, when I commented out the delay function in the batchInsert file, it works

**Comment by Ygilany** [comment] 2019-12-10 14:59
@elhigu more info is added, please re-open

**Comment by maximelkin** [comment] 2019-12-10 19:14
@Ygilany by default jest uses jsdom for running tests

**Comment by elhigu** [comment] 2019-12-10 21:13
@Ygilany that reproduction should depend only from knex package (and preferably be single runnable file)... problem you are encountering still might be caused by something else (for example the thing that @maximelkin pointed out)

**Comment by MigFerreira** [comment] 2020-04-20 17:00
Exact same issue as described above.

Removing await delay(1) from knex/lib/util/batchInsert.js solved my problem.

Hard to diagnose problem since no error pops up.

**Comment by erhathaway** [comment] 2020-04-21 20:38
@elhigu I'm also experiencing this in Knex 0.20.13. I'm not using Bookshelf or another wrapper lib.

**Comment by elhigu** [comment] 2020-04-22 08:49
@erhathaway good to know. I'm also still experiencing lack of proper reproduction code.
