### ISSUE TITLE
migrate:latest throws famous timeout error "The pool is probably full."

### ISSUE THREAD

**Issue by o1dnik** [knex/knex#4075] opened 2020-10-22 18:30 UTC
# Environment

Knex 0.21.6  or  0.21.1
Postgres 12 on DigitalOcean Managed Database or local machine also v.12.4
Ubuntu 20.04.1 LTS on DigitalOcean Droplet  or  MacOS Catalina local machine
Node:  15.0.1 or 14.14.0

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

On running knex migrate:latest I get `KnexTimeoutError` exception which may have multiple reasons as I learned. What I expect though is to have the migrations pass as it does on my local machine MacOS Catalina 10.15.7 with the same package versions. Tested with many combinations including version of nodejs.

2. Error message

```bash
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_PG.acquireConnection (/root/api/node_modules/knex/lib/client.js:349:26)
    at async Promise.all (index 1)
```
or
```bash
error: no pg_hba.conf entry for host "<IP of the Droplet here>", user "doadmin", database "defaultdb", SSL off
    at Parser.parseErrorMessage (/root/api/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/root/api/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/root/api/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/root/api/node_modules/pg-protocol/dist/index.js:10:42)
```
in case if I change the `ssl` parameter in the options I pass to knex.

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

The knexfile.js

```js
const config = require("config")
const { knexSnakeCaseMappers } = require("objection")
const { parse } = require("pg-connection-string")
const pgConfig = parse(config.get("postgresql.url"))

module.exports = {
  db: pgConfig,
  client: "postgresql",
  connection: {
    host: pgConfig.host,
    user: pgConfig.user,
    password: pgConfig.password,
    database: pgConfig.database,
    port: pgConfig.port,
    // ssl: true,
  },
  // acquireConnectionTimeout: 5 * 60 * 1000, // =5min
  debug: false,
  asyncStackTraces: process.env.NODE_ENV === "development",
  pool: {
    min: 2,
    max: 10,
    // propagateCreateError: false,
  },
  ...knexSnakeCaseMappers(),
}
```

...which is then required in dbmanager.js file

```js
const knexfile = require("./knexfile")

const dbManager = require("knex-db-manager").databaseManagerFactory({
  knex: knexfile,
  dbManager: {
    superUser: knexfile.db.user,
    superPassword: knexfile.db.password,
  },
})
```

...and then loading a simple Express server.js where it is stuck on this point:

```js
await dbManager.dbVersion()
```

if I do not do **migration** of the schema to Postgres. But funny enough **on my local machine migration works fine**, while on **DigitalOcean Managed Database** postgres + single Droplet with Ubuntu 20.04.1 and nginx (all setup and working with a minimal HelloWorld example, but not yet with the complete app) - >**migration fails**< with these errors, timeout or pb_hba.conf.

Here's the comments, articles and documentation I have passed through so far:

 - DigitalOcean Managed Database configuration to add trusted sources so that Droplet and DB are in the same network and trust each other [article here](https://www.digitalocean.com/docs/databases/postgresql/how-to/secure/#firewalls)
 - Useful [comment](https://github.com/knex/knex/issues/3831#issuecomment-648736333) regarding the `KnexTimeoutError` reasons
 - [comment](https://github.com/knex/knex/issues/2820#issuecomment-481710112) regarding `propagateCreateError` parameter which allows to attempt to reconnect
 - comments about ssl parameter and self signed certificate [here](https://github.com/brianc/node-postgres/issues/2009)
 - recommended and confirmed by others [versions of npm](https://stackoverflow.com/a/61482183/1598355) packages which remove the timeout error for others (not for me)
 - checking up `rejectUnauthorized` and DATABASE_URL on [DO community](https://www.digitalocean.com/community/questions/can-t-connect-to-managed-database-self_signed_cert_in_chain-error)
 - postgres documentation about SSL support [here](https://www.postgresql.org/docs/9.1/libpq-ssl.html)
 - few [comments](https://www.digitalocean.com/community/questions/postgres-managed-db-require-pg_hba-conf) on DO regarding pg_hba.conf issue
 - a [useful note](https://www.digitalocean.com/community/questions/cannot-connect-my-postgresql-db-to-my-netcore-project?answer=57903) about .crt certificate which could be obtained for the database and put on the Droplet manually to ensure secure connection to Postgres
 - the [original tutorial](https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-20-04) from DO on how to setup Ubuntu 20 with Express server on a Droplet

I am literally out of options what to try next.

**Comment by elhigu** [comment] 2020-10-23 08:46
I think you should ask support for this from digital ocean forums or stackoverflow. Knex's issue tracker is for bugs and feature requests and other development use only. Though if someone likes to help please keep on discussing here even that the issue is closed.

Closing as kenx usage question.

**Closed by elhigu** 2020-10-23 08:46 UTC

**Comment by Offirmo** [comment] 2020-11-09 17:01
This is likely the known issue of a breaking change in the underlying node-postgres + node 14 https://github.com/brianc/node-postgres/blob/master/CHANGELOG.md#pg800

Solution:
- go back to node 12 and pg@^7
- or manage to activate SSL with proper certificates all along

**Comment by cliedeman** [comment] 2021-01-13 09:17
I can also verify that this issue happens. In my case it was with a local postgres docker image.

Rolling back to node 12 resolve it for now. Did not test if updgrading node-postgres would fix it
