### ISSUE TITLE
Error [KnexTimeoutError]: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?

### ISSUE THREAD

**Issue by ewax** [knex/knex#4519] opened 2021-06-10 06:21 UTC
# Environment

Knex version: "^0.95.6"
PG: "^8.6.0"
Next: "^10.2.3"
OS: macOS

# Bug

I'm working several months on my project. Since yesterday I get suddenly the error: "Error [KnexTimeoutError]: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?".

I've seen that others had similar issues with node 14 and knex <8.X. But I'm not using these versions (see above). 

My DB is hosted on Heroku. There seem to be no issue with connection limit - connections are usually available.

Heres some relevant code:
**knexfile.js**

```
module.exports = {
  development: {
    client: 'pg',
    connection: {
      database: process.env.DATABASE,
      user: process.env.DATABASE_USER,
      password: process.env.DATABASE_PASSWORD,
      host: process.env.DATABASE_HOST,
      port: process.env.DATABASE_PORT,
      ssl: { rejectUnauthorized: false },
    }
  }, 
 
  production: {
    client: 'postgresql',
    connection: {
      database: process.env.DATABASE,
      user: process.env.DATABASE_USER,
      password: process.env.DATABASE_PASSWORD,
      host: process.env.DATABASE_HOST,
      port: process.env.DATABASE_PORT,
      ssl: { rejectUnauthorized: false },
    },
    pool: {
      min: 0, 
      max: 20
    },
  }
};
```
The error comes and goes. Does someone know what to look for?

**Comment by waqarmm** [comment] 2021-07-03 21:04
I am having the same issue on heroku  server. IT was working before

**Comment by elhigu** [comment] 2021-07-05 10:13
```
elhig@LAPTOP-1UTU920J MSYS ~/Projects/myherokuproject (master)
$ npm list
finscalper@1.0.0 C:\Users\elhig\Projects\myherokuproject 
├── axios@0.21.1
├── dotenv@8.6.0
├── heroku@7.54.0
├── knex@0.95.6
├── luxon@1.27.0
├── pg-escape@0.2.0
└── pg@8.6.0

const knex = require('knex')({
  client: 'pg',
  connection: {
    connectionString: process.env.DATABASE_URL,
    ssl: {
      rejectUnauthorized: false
    }
  }
});
```
Configuration above works for me.  May be an user error of opening transactions but not not ending them or something like that.

Try to disable code from your heroku app until that problem disappears and then start looking that code if there is a problem...

Closing as cannot reproduce, Can be reopened if complete test case is provided.

**Closed by elhigu** 2021-07-05 10:13 UTC
