### ISSUE TITLE
Ban select on typing, for readonly knee connecition

### ISSUE THREAD

**Issue by jpike88** [knex/knex#3767] opened 2020-03-31 12:49 UTC
I have these two variables:
```

let knex: knexFactory;
let knexReadOnly: knexFactory;

```

One is a writer, one is a reader. I want to be able to easily ban select statements on the reader. Any techniques?

**Comment by elhigu** [comment] 2020-03-31 13:15
Closing knex usage question. Please feel free to discuss subject here even that the issue is closed.

**Closed by elhigu** 2020-03-31 13:15 UTC

**Comment by wubzz** [comment] 2020-03-31 13:58
Don't think there's any good way of doing this in knex. Suppose best would be to use different database users that are setup accordingly.

Checking the builder's type _(select/insert/update/etc)_ and throwing errors won't hold since we also have `RAW`. This kind of feature is out of library-scope I would say.

One workaround that _might_ work is to use [afterCreate](https://knexjs.org/#Installation-pooling-afterCreate) and call 
```sql
SET SESSION CHARACTERISTICS AS TRANSACTION READ ONLY;
```

Untested, but maybe. _(Postgres)_

**Comment by jpike88** [comment] 2020-03-31 14:45
I think the discussion in #2253 is more relevant to my needs, I shouldn't be trying to solve this at the type level anyway I think
