### ISSUE TITLE
Nested Columns in Query Result

### ISSUE THREAD

**Issue by kferrone** [knex/knex#3630] opened 2020-01-20 21:19 UTC
is it possible to control how the object returned by a query is shaped? I want to group some of the columns in a query into their own property of the result. 

For example we have the following table:

User Table:
```
first_name, middle_name, last_name, favorite_food, role
```

Basically I want to query the result to be like so:

```json
{
    "name": {
        "first": "bob",
        "middle": "j",
        "last": "dude",
    },
    "favorite_food": "pizza",
    "role": "boss"
}
```

Unfortunately I can only get the result to have flat properties like so:

```json
{
    "name_first": "bob",
    "name_middle": "j",
    "name_last": "dude",
    "favorite_food": "pizza",
    "role": "boss"
}
```

Here is what I thought would work:

```js
knex.first({
    name: {
        first: "first_name",
        middle: "middle_name"
        last: "last_name"
    },
    favorite_food: "favorite_food",
    role: "role"
})
.from("users");
```

Unfortunately it fails when it tries to say something like:
```
first_name as first as name
SQLITE_ERROR: near "as": syntax error
```

Can this be done at all or do I just have to build my own object using the result of knex?

**Comment by elhigu** [comment] 2020-01-20 21:51
No. Knex doesn't have any support like that and I have no idea why would you have thought that would have worked. There is nothing in documentation of anything like that 🤔  Closing as this is not a bug nor feature request.

**Closed by elhigu** 2020-01-20 21:51 UTC
