### ISSUE TITLE
ER_NO_REFERENCED_ROW_2: Cannot add or update a child row when using knex seed:run

### ISSUE THREAD

**Issue by pruhstal** [knex/knex#947] opened 2015-08-25 07:50 UTC
Using knex:seed run. Ran migrations previously. Is this because of the order the seeds are running? If so, is there a way to run one at a time (`knex -h` didn't mention anything about running standalone seeds).

**Migrations** 

`migrations/20150706171358_users.js`

```
exports.up = function (knex, Promise) {
  return knex.schema.createTable('users', function (table) {
    table.increments('id');
    table.string('email').notNullable().unique();
    table.string('hash', 64).notNullable();
    table.string('username', 23).notNullable().unique();
    table.string('name', 32).nullable();
    table.enum('role', ['normal', 'admin']).notNullable();
    table.string('about').nullable();
    table.timestamp('created_at').notNullable();
    table.timestamp('updated_at');
    table.enum('gender', ['M', 'F', 'O']).nullable();
    table.integer('created_ip', 10);
    table.string('photo', 36).nullable();
    table.boolean('confirmed', 0);
    table.string('confirm_code', 64).notNullable();
  });
};

exports.down = function (knex, Promise) {
  return knex.schema.dropTable('users');
};
```

`migrations/20150807001656_user_password_resets.js`

```
exports.up = function (knex, Promise) {
  return knex.schema.createTable('user_password_resets', function (table) {
    table.increments('id');
    table.integer('user_id').unsigned().references('users.id');
    table.string('email').unique();
    table.string('reset_token', 64).notNullable();
    table.timestamp('created_at').notNullable().defaultTo(knex.raw('now()'));
    table.timestamp('updated_at');
    table.integer('attempts').notNullable().defaultTo(0);
  });
};

exports.down = function (knex, Promise) {
  return knex.schema.dropTable('user_password_resets');
};
```

`migrations/20150825001204_user_email_notifications.js`

```
exports.up = function (knex, Promise) {
  return knex.schema.createTable('user_email_notifications', function (table) {
    table.increments('id');
    table.integer('user_id').unsigned().references('users.id');
    table.boolean('new_follower');
    table.boolean('new_message');
    table.boolean('new_comment);
    table.boolean('new_notification');
    table.boolean('digest');
    table.boolean('updates');
    table.timestamp('created_at').notNullable().defaultTo(knex.raw('now()'));
    table.timestamp('updated_at');
  });
};

exports.down = function (knex, Promise) {
  return knex.schema.dropTable('user_email_notifications');
};
```

**Seeds**
`seeds/user_email_notifications.js`

```
exports.seed = function (knex, Promise) {
  return Promise.join(
      // Deletes ALL existing entries
      knex('user_email_notifications').del(),

      // Inserts seed entries
      knex('user_email_notifications').insert({
        id: 1,
        user_id: 1,
        new_follower: 1,
        new_message: 1,
        new_comment: 1,
        new_notification: 1,
        digest: 1,
        updates: 1,
        created_at: new Date(),
        updated_at: new Date()
      })
  );
};
```

`seeds/user_password_resets.js`

```
exports.seed = function (knex, Promise) {
  return Promise.join(
      // Deletes ALL existing entries
      knex('user_password_resets').del(),

      // Inserts seed entries
      knex('user_password_resets').insert({
        id: 1,
        user_id: 1,
        email: 'test@example.com',
        reset_token: '7ab4b03069096561afb09c70619177ac0af869629d446b0b',
        created_at: new Date(),
        updated_at: new Date()
      })
  );
};
```

`seeds/users.js`

```
exports.seed = function (knex, Promise) {
  return Promise.join(
      // Deletes ALL existing entries
      knex('user_password_resets').del(),

      // Inserts seed entries
      knex('user_password_resets').insert({
        id: 1,
        user_id: 1,
        email: 'test@example.com',
        reset_token: '7ab4b03069096561afb09c70619177ac0af869629d446b0b',
        created_at: new Date(),
        updated_at: new Date()
      })
  );
};
```

Anyone else having this issue when using `knex` cli?

**Comment by Alex-Mann** [comment] 2016-10-24 01:20
I have the same issue and I've debugged it to figure out that it is the order in which the CLI is executing the seed files. Is there a way to specify the order to have them run?

**Comment by sandobits** [comment] 2020-11-12 05:16
Unfortunate to see this hasn't been closed or addressed since 2016. I'm having this exact same error with similar migration files and MySQL module (works fine with sqlite3 on different servers though).
Seems like a compatibility issue specific to mysql foreign keys, as seen in [this post from StackOverflow](https://stackoverflow.com/questions/21659691/error-1452-cannot-add-or-update-a-child-row-a-foreign-key-constraint-fails), which brings me to the same doubt Alex had before me: can I select the order on which the migrations and seeds are executed? I'm trying to run them in a production environment, so how do I configure that with a package.json script?

**Comment by elhigu** [comment] 2020-11-12 07:29
Thanks for reminder to close this. The running order of seeds is addressed. Migrations and seed are ran in alphabetical order. https://github.com/knex/knex/blob/master/lib/seed/Seeder.js#L68 

Currently this looks like an user error. If you see something like this happening, please open new bug report with reproduction of the code that causes the error.

**Closed by elhigu** 2020-11-12 07:29 UTC
