### ISSUE TITLE
query results using @var is different between knex and mysql

### ISSUE THREAD

**Issue by LiuWei-Luke** [knex/knex#3862] opened 2020-05-21 06:29 UTC
# Environment

Knex version:  0.12.6
Database + version: Mysql: 5.6
OS: centos

# Bug

I'm trying to use some @var in my knex query, but it didn't work well, Here is my usecase below.
```javascript
 let select = `select id, batch, row_number
  from (
    SELECT @row_numbers:= CASE WHEN @staff_id=staff_no THEN @row_numbers+1 ELSE 1 END as row_number,
    @batch:= @row_numbers / 5 as batch,
    @staff_id:= staff_no as staff_id,
    task_id,
    store_no,
    id
    from table
    where
      task_id='${taskId}'
    AND
    order by staff_no
  ) as a
  where batch <= 1
  `
  return knex.raw(select).then(result=>result[0])
```
But result was not same as using query in mysql directly,  I thought @row_numbers didn't +1 in knex query.

**Comment by elhigu** [comment] 2020-05-22 10:45
Please add complete reproduction. That is not runnable example. Closing since it doesn't seem like a knex issue. Also I'm not sure at all what `result=>result[0]` should return from `knex.raw` query. Try to run that query directly with mysql driver to see if it works there as excepted.

**Closed by elhigu** 2020-05-22 10:45 UTC
