### ISSUE TITLE
Knex can not get the newest data after update.

### ISSUE THREAD

**Issue by dadiorchen** [knex/knex#4523] opened 2021-06-14 03:08 UTC
# Environment

Knex version: knex@0.21.5
Database + version: Postgresql 11
OS: MacOS

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do
  New connection got stale data from DB, the code sequence is:
  1. Update table1 (await the promise to be solved)
  2. Get a new knex connection, the way to get the connection is below:
```
const knex = require('knex')({
  client: 'pg',
  debug: process.env.NODE_LOG_LEVEL === "debug",
  connection,
  pool: { 
    min:0, 
    max: 100,
    afterCreate (conn, done) {
      conn.query('SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL SERIALIZABLE;', function (err) {
        if (err) {
          log.error(err)
          done(err, conn)
        } else {
          log.debug('SERIALIZABLE isolation level set successfully')
          done(err, conn)
        }
      });
    }
  }
})
```
  3. Select data from the table
  4. Still got the stale data before the update.
  5. I double-checked the code, I'm sure I used `await` to wait for the update to finish.
  6. If I use something like `sleep` to block the code for a while, then I can get the newest/updated data.

2. Error message
   No error throwing

**Comment by elhigu** [comment] 2021-06-14 11:08
Please add complete reproduction code. Doesn't sound like a knex issue. You should not even need to set `TRANSACTION ISOLATION LEVEL SERIALIZABLE` to haave that cycle work where you do update, commit, select and have the latest data in select.

postgresql is ACID so so that guarantees that after the transaction where update is made is committed the next select will return the updated data.

Closing since currently nothing points this behavior being bug in knex and cannot reproduce.

**Closed by elhigu** 2021-06-14 11:08 UTC

**Comment by dadiorchen** [comment] 2021-06-15 08:52
@elhigu Thanks, yes, eventually I found the problem, it's not a problem of knex, I can put my problematic code here to give people a bad case:
```
      res.status(200).json(transferJson2);
      await session.commitTransaction();
```

Here `res` is `Express` response object. So I commit the database transaction too later, when I move the below line to the above, I get the correct result.
