### ISSUE TITLE
Cannot read property 'type' of undefined 

### ISSUE THREAD

**Issue by davidrtpereira** [knex/knex#3602] opened 2019-12-31 10:14 UTC
Error executing query on table with column with data type CLOB.

```
process.version
'v12.14.0'

process.arch
'x64'

require('oracledb').versionString
'4.1.0'

require('oracledb').oracleClientVersionString
'11.2.0.4.0'
```

What is your Oracle Database version?
11G

Table Structure SQL

```
CREATE TABLE "CAPTURA"."CAPTURA_XML" 
   (	"CHNFE" VARCHAR2(44 BYTE), 
	"XML" CLOB NOT NULL ENABLE, 
	 PRIMARY KEY ("CHNFE"))
```

Error:

![image](https://user-images.githubusercontent.com/20539715/71599095-38367280-2b28-11ea-8512-d5b1d06a941d.png)

console.log **stream** variable:

https://gist.github.com/davidrtpereira/3f6b4e152d898018dcc15974858af757

Modificated lines 340 and 349 to node_modules\knex\lib\dialects\oracledb\index.js, returned success in query:
https://gist.github.com/davidrtpereira/d5a66fd53becc443fd291f54f8963f37

![image](https://user-images.githubusercontent.com/20539715/71599756-ef33ed80-2b2a-11ea-9950-4a477e87641b.png)

**Comment by kibertoad** [comment] 2020-01-04 23:18
@davidrtpereira What knex version are you using?

**Comment by davidrtpereira** [comment] 2020-01-06 18:05
0.20.6

**Comment by elhigu** [comment] 2020-01-06 21:16
Did I understood correctly that there is missing test that `stream.iLob` actually exist? What could cause `stream.iLob` to be undefined or are we just missing an integration test for this?

**Comment by kibertoad** [comment] 2020-01-07 00:37
TBH, that doesn't look like 0.20.6 at all: first of all, it is clearly transpiled with Babel, second, current relevant code looks like this:
```
  if (stream.type) {
    // v1.2-v4
    if (stream.type === oracledb.BLOB) {
      type = 'buffer';
    } else if (stream.type === oracledb.CLOB) {
      type = 'string';
    }
  } else if (stream.iLob) {
    // v1
    if (stream.iLob.type === oracledb.CLOB) {
      type = 'string';
    } else if (stream.iLob.type === oracledb.BLOB) {
      type = 'buffer';
    }
```

As you can see, it includes check for `stream.iLob` already, while the code that you were fixing does not. Please check that knex version is indeed what you expect it to be and there are no additional versions of knex being transitively resolved as dependencies, being installed globally etc.

**Comment by kibertoad** [comment] 2020-01-07 00:37
Latest version of knex should work with Oracle CLOBs just fine.

**Comment by elhigu** [comment] 2020-01-07 06:40
Closing as cannot reproduce for now. As @kibertoad investigated doesnt seem to be bug in knex.

**Closed by elhigu** 2020-01-07 06:40 UTC
