### ISSUE TITLE
Unhandled promise rejection in knex/lib/transaction.js - ORA-03135: connection lost contact / NJS-003: invalid connection

### ISSUE THREAD

**Issue by amroczeK** [knex/knex#4113] opened 2020-11-06 02:30 UTC
# Environment

Knex version: 0.21.12
Database + version: Oracle 11g @atiertant 
OS: Docker build using centos:7.6.1810
Node version: v12.18.0
Npm version: 6.14.4

If issue is about oracledb support, tag @atiertant.
@elhigu 

# Bug

Intermittently receiving this error when trying to run an SQL query from my application to Oracle db using Knex.

Really hard to diagnose why/how it is happening, but when it does happen I am unable to do any further queries and have to restart the docker container which will re-create the Knex connection and pool.

Seems like the error is occurring directly inside knex/lib/transaction.js:194:35 when trying to execute the query using the pool.

```
Error: select * from (with "with_alias" as (select ' ______' as ecell_name,'Dummy cell for chart suppression','______________________________' from dual
union all
select ecell_name, enodeb_name, base_station_name
from ECELL_TARGET_QH_MVW
where substr(ecell_name,6,1) <> 'I'
order by 1
) select * from "with_alias") where rownum <= :1 - ORA-03135: connection lost contact
Process ID: 100345
Session ID: 7889 Serial number: 56971 for SQL query against Bilby
(node:2495) UnhandledPromiseRejectionWarning: Error: NJS-003: invalid connection
at Connection.rollback (/home/node/server/node_modules/oracledb/lib/connection.js:159:14)
at Connection.rollback (/home/node/server/node_modules/oracledb/lib/util.js:181:10)
at /home/node/server/node_modules/knex/lib/dialects/oracledb/index.js:130:16
at new Promise (<anonymous>)
at Connection.connection.rollbackAsync (/home/node/server/node_modules/knex/lib/dialects/oracledb/index.js:129:16)
at Oracle_Transaction.rollback (/home/node/server/node_modules/knex/lib/dialects/oracledb/transaction.js:28:25)
at Function.transactor.rollback (/home/node/server/node_modules/knex/lib/transaction.js:278:42)
at /home/node/server/node_modules/knex/lib/transaction.js:194:35
(node:2495) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:2495) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

# Possible causes
The Oracle Database my application connects to does have a script running which will kill inactive sessions for a particular user, there is also a script which will kill users connection to the database after inactivity. I will be receive a message asking to Reconnect stating "Your database connection has been reset. Any pending transactions or session state has been lost".

I've also experienced this reconnect in SQL Developer happening intermittently even a few minutes after running a query and re-running it again. 

I have requested my robot user to be omitted from the scripts killing inactive sessions and dropping connections after inactivity. Will continue testing after the change request is complete.

# Question

- Do you have any ideas why/how this could be happening or seen this issue occur before, or any tips to help troubleshoot this?

- What is the expected behavior of Knex when an inactive Oracle session is killed in Oracle DB? Does tarn drop the connection from the pool?

- Is there a way I can validate a connection in the pool is usable/still available before a query is executed?

# My Code
```
const _knex = require("knex");

let connections = {};

const querySQL = async (datasource, sql, format, modifier, chartType) => {
  const knex = await findOrCreateConnection(datasource);

  let count = knex.client.pool.numUsed();
  if (count > 4) console.log(`--- Numb connections used from pool: ${count}`);

  try {
    const result = await knex.transaction(async (trx) => {
      try {
          const result = await trx.raw(sql).timeout(90000);
          return result;
      } catch (error) {
        console.log(
          `${error.toString()} for SQL query against ${datasource.name}`
        );
        throw error;
      }
    });
    return result;
  } catch (error) {
    throw error;
  }
};

const getConnectionObj = (datasource) => {
  switch (datasource.databaseType) {
    case "oracledb":
      return {
        client: datasource.databaseType,
        connection: {
          host: datasource.host,
          user: datasource.user,
          password: datasource.password,
          database: datasource.database,
        },
        pool: { min: 5, max: 33 },
      };
    case "sqlite3":
      if (datasource.filename && datasource.filename.length > 0) {
        return {
          client: "sqlite3",
          connection: {
            filename: "./packages/" + datasource.filename,
          },
          useNullAsDefault: true /* Supress sqlite3 warning*/,
        };
      } else {
        return false;
      }
    default:
      return {
        client: datasource.databaseType,
        connection: {
          host: datasource.host,
          user: datasource.user,
          password: datasource.password,
          database: datasource.database,
        },
        pool: { min: 2, max: 10 },
      };
  }
};

const findOrCreateConnection = async (datasource) => {
  // If the Knex connection already exists
  try {
    if (connections[datasource.name]) {
      //console.log(`${datasource.name} already available.`);
      return connections[datasource.name];
    }
    // Establish a new connection
    else {
      const connObj = getConnectionObj(datasource);
      const newConnection = _knex(connObj);	// Create knex connection
      connections[datasource.name] = newConnection;
      return newConnection;
    }
  } catch (error) {
    console.log(error);
    throw error;
  }
};

module.exports = {
  querySQL
};
```

**Also is there anything wrong with writing a transaction like this?**
```
try {
  const result = await knex.transaction(async (trx) => {
    try {
      const result = await trx
        .with("with_alias", trx.raw(queriedSql)) // <--- Is this there anything wrong with this?
        .select("*")
        .from("with_alias")
        .whereRaw(aliasedWhereClause)
        .limit(modifier.limit || 10000)
        .timeout(90000);
      return result;
    } catch (error) {
      console.log(
        `${error.toString()} for SQL query against ${datasource.name}`
      );
      throw error;
    }
  });
  return result;
} catch (error) {
  throw error;
}
```

**Comment by amroczeK** [comment] 2020-11-10 02:15
I think this issue is isolated to my local development and NGINX reverse-proxy/docker networking because this issue isn't occurring in production after upgrading Knex to 0.21.12.

**Comment by elhigu** [comment] 2020-11-10 14:23
If you are able to find minimal reproducible example please share. Closing for now, since there is nothing that we can do/fix in knex  to make this work.

**Closed by elhigu** 2020-11-10 14:23 UTC
