### ISSUE TITLE
Internal/crypto/keys.js TypeError [err_invalid_arg_type]

### ISSUE THREAD

**Issue by EEZHI** [knex/knex#4067] opened 2020-10-16 18:48 UTC
Knex version: 0.21.6
Database + version: postgresql (v13)
OS: Windows 10

Hi, I'm having issues running "knex migrate:latest", "knex migrate:list", "knex migrate:rollback" but i'm able to run"knex migrate:make". Ordinarily i shouldn't have any issues running this, since i'm following a tutorial video on a similar application but i keep getting this error message for each of the commands above. 

$ knex migrate:latest
Using environment: development
internal/crypto/keys.js:305
throw new ERR_INVALID_ARG_TYPE(
^

TypeError [ERR_INVALID_ARG_TYPE]: The “key” argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received null
at prepareSecretKey (internal/crypto/keys.js:305:13)
at new Hmac (internal/crypto/hash.js:113:9)
at Object.createHmac (crypto.js:143:10)
at createHMAC (C:\Users\EEZHI\database2\node_modules\pg\lib\sasl.js:133:17)
at Hi (C:\Users\EEZHI\database2\node_modules\pg\lib\sasl.js:137:13)
at Object.continueSession (C:\Users\EEZHI\database2\node_modules\pg\lib\sasl.js:32:24)
at Client._handleAuthSASLContinue (C:\Users\EEZHI\database2\node_modules\pg\lib\client.js:248:10)
at Connection.emit (events.js:315:20)
at C:\Users\EEZHI\database2\node_modules\pg\lib\connection.js:109:12
at Parser.parse (C:\Users\EEZHI\database2\node_modules\pg-protocol\dist\parser.js:40:17) {
code: ‘ERR_INVALID_ARG_TYPE’
}

I've also created new database files trying to run those commands and they still produce the same results. Any ideas on how I can fix this error? thanks

**Comment by elhigu** [comment] 2020-10-17 19:30
Please provide reproduction code for this. Closing until repro is provided.

**Comment by kamclark** [comment] 2020-11-02 05:17
I have the same problem, can `knex migrate:make` but can not `knex migrate:latest`

the code and screenshot of error are here:

https://github.com/kamclark/knex-windows-problem

> Please provide reproduction code for this. Closing until repro is provided.

**Comment by elhigu** [comment] 2020-11-03 11:01
Could you show what that code outputs if you run it with DEBUG=knex:* environment variable set? Also you could try if you are able to connect that database at all by using directly `node-pg` driver. Just to rule out the option that the problem is coming from driver instead of knex.

**Comment by kamclark** [comment] 2020-11-03 20:17
figured it out.
this is stemming from `node-pg` driver as you mentioned and not properly setting password.

password being undefined or null in my *knexfile.js*: `TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be one of type Buffer, TypedArray, DataView, string, or KeyObject. Received type object`

wrong password: `error: password authentication failed for user "postgres"`

correct password: `Batch 1 run: 1 migrations`

**Closed** 2020-11-04 14:08 UTC
Labels: More information requested
