### ISSUE TITLE
 Add a new chain for lateral join to joins support

### ISSUE THREAD

**Issue by meftunca** [knex/knex#4621] opened 2021-08-14 11:36 UTC
# Environment

Knex version: 0.95.8
Database + version: PostgreSQL +  13.2
OS: MACOS

# Feature discussion / request

Add a new chain for lateral join to joins support

**Comment by OlivierCavadenti** [comment] 2021-11-09 08:18
Duplicate of https://github.com/knex/knex/issues/3732

**Closed by OlivierCavadenti** 2021-11-09 08:18 UTC
