### ISSUE TITLE
Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?

### ISSUE THREAD

**Issue by imjgautam** [knex/knex#6027] opened 2024-03-07 13:24 UTC
# Environment

Knex version: "knex": "^3.1.0",
pg version: "pg": "^8.0.3",
Database + version: Postgres 16.2
OS: Ubuntu
Node js version : 12, 14, 16, 18, 19

# Bug
![WhatsApp Image 2024-02-27 at 4 39 29 PM](https://github.com/knex/knex/assets/26070273/09889d86-f57d-46cd-a1e1-81703a8b095e)

1. Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?

2. DB automatically shut down.

3. Idle session timeout error.

Please any one has the solution about these querry, I am facing this issue from last 2 months, I need to fix it. Please share the solution, I have downgraded the node js version also, but not worked, I also configured all pool object in knex but not worked, even i implemented COMMIT, ROLLBACK, DESTROY, RELEASE, buth nothing worked.

**Comment by rluvaton** [comment] 2024-03-14 21:20
I know this issue was created before #6034 but I already answered there

Duplicate of #6034

**Closed by rluvaton** 2024-03-14 21:20 UTC
