### ISSUE TITLE
Not Able To Create A Table

### ISSUE THREAD

**Issue by yonderbread** [knex/knex#3976] opened 2020-08-12 01:39 UTC
I'm unable to create a table with the following bit of code:

```js
database.schema.hasTable('requests').then(function (exists) {
  if (!exists) {
    log.success('Creating table?')
    return database.schema.createTable('requests', table => {
        table.increments('id').primary().notNullable();
        table.text('requestName', 'mediumtext').notNullable();
        table.text('requestType').notNullable();
        table.text('userSnowflake').notNullable();
        table.timestamp('created_at').notNullable();
      }
    ).then(() => {
      log.success(database.select('requestName').from('requests'))
    }).catch(log.failure);
  }
})
```

I'm getting this error...
```sqlite does not support inserting default values. Set the `useNullAsDefault` flag to hide this warning. (see docs http://knexjs.org/#Builder-insert).```

When I query the sqlite database in DataGrip it does not show any tables.

**Comment by elhigu** [comment] 2020-08-12 08:38
Are you getting any other debug prints from your test code? That warning `sqlite does not support inserting default values. Set the useNullAsDefaul flag to hide this warning. (see docs http://knexjs.org/#Builder-insert).` you mentioned has nothing to do with tables not being created. Please also add complete reproduction code. 

Now there is no way to know how you are trying to create DB and verifying its existence... Also if table already exists that app doesn't print anything.

Closing as this seems an user error and not a bug in knex. Can be reopened if more info is provided showing that there indeed is a bug in knex.

**Closed by elhigu** 2020-08-12 08:38 UTC
