### ISSUE TITLE
Transaction execution order issue

### ISSUE THREAD

**Issue by MagsMagnoli** [knex/knex#4650] opened 2021-08-26 20:08 UTC
# Environment

Knex version: 0.95.10
Database + version: pg 8.7.1
OS: Linux

# Bug
Since 0.20.11 there is a transaction synchronization issue. On a production workflow even with forUpdate locking this causes data to be read and executed on out of order. The transaction is rearranged to the proper order after the commit but with values that 'arent possible' if it had been executed sequentially.

1. Create simple loop where transactions are used and log their execution
2. Notice that for a moment the transactions occur out of order leading to corrupted data

Simple repro code:

```
const db = knex({
  client: "postgresql",
  connection: "{{connection}}",
  pool: {
    min: 2,
    max: 10,
  }
});

async function insert(iteration: number) {
  return db.transaction(async (tx: any) => {
    logger.debug(`STARTING CONNECTION ${iteration}`);
  });
}

for (let i = 0; i < 10; i++) {
  insert(i);
}
```

|**0.20.10**|**0.20.11+**|
|---|---|
|`2021-08-26T19:49:20.446Z [debug]: STARTING CONNECTION 0`|`2021-08-26T19:47:37.918Z [debug]: STARTING CONNECTION 0`|
|`2021-08-26T19:49:20.447Z [debug]: STARTING CONNECTION 1`|`2021-08-26T19:47:37.919Z [debug]: STARTING CONNECTION 1`|
|`2021-08-26T19:49:20.447Z [debug]: STARTING CONNECTION 2`|`2021-08-26T19:47:37.920Z [debug]: STARTING CONNECTION 2`|
|`2021-08-26T19:49:20.447Z [debug]: STARTING CONNECTION 3`|`2021-08-26T19:47:37.920Z [debug]: STARTING CONNECTION 3`|
|`2021-08-26T19:49:20.447Z [debug]: STARTING CONNECTION 4`|`2021-08-26T19:47:37.921Z [debug]: STARTING CONNECTION 4`|
|`2021-08-26T19:49:20.447Z [debug]: STARTING CONNECTION 5`|`2021-08-26T19:47:37.924Z [debug]: STARTING CONNECTION 6`|
|`2021-08-26T19:49:20.447Z [debug]: STARTING CONNECTION 6`|`2021-08-26T19:47:37.924Z [debug]: STARTING CONNECTION 7`|
|`2021-08-26T19:49:20.450Z [debug]: STARTING CONNECTION 7`|`2021-08-26T19:47:37.925Z [debug]: STARTING CONNECTION 8`|
|`2021-08-26T19:49:20.450Z [debug]: STARTING CONNECTION 8`|`2021-08-26T19:47:37.925Z [debug]: STARTING CONNECTION 9`|
|`2021-08-26T19:49:20.451Z [debug]: STARTING CONNECTION 9`|`2021-08-26T19:47:37.926Z [debug]: STARTING CONNECTION 5`|

**Comment by maximelkin** [comment] 2021-08-28 02:23
I will try, but no guaranties i will succeed, sorry in advance

**Comment by maximelkin** [comment] 2021-08-28 03:02
Locally tested, `BEGIN;` query finish not in the ascending order, dont think it wrong behavior.
Can you please provide more info?

Also await before insert supposed to be omitted? (i tested both, `await` variant constantly provide sequential results as expected)

**Comment by MagsMagnoli** [comment] 2021-08-28 14:30
@maximelkin sure

In our real use case we use a row lock before reading then writing the difference in a status change. What we write is `old_status` `new_status`. We use an await before the row lock, before the read, and before the write.

What happens is the item that is out of order, say 5 coming after 7, 5 will read the data from number 7 then its `old_status` will be what 7 wrote. After all the transactions are done they get re-ordered such that 5 now comes before 7, but it has 7's data, making the write an 'impossible' transition. 

An example output looks like this. Note the rows go from bottom to top where the value of the right column should be the value of the left at the higher row:
![image](https://user-images.githubusercontent.com/4146037/131221343-28a06fcd-3d0e-4ec3-ab85-d3ed3fadf833.png)
But when we roll back to the earlier version:
![image](https://user-images.githubusercontent.com/4146037/131221351-4b7b0542-4a9b-4d42-8de1-b1fb165139c9.png)

**Comment by MagsMagnoli** [comment] 2021-08-28 14:52
Heres the code for a slightly more complex example:

Migration file for db:
```
-- migrate:up
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;

CREATE TABLE public.items (
    id uuid DEFAULT public.gen_random_uuid() NOT NULL PRIMARY KEY,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


CREATE TABLE public.item_status_events (
    id uuid DEFAULT public.gen_random_uuid() NOT NULL PRIMARY KEY,
    item_id uuid NOT NULL REFERENCES items,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    old_status int NOT NULL DEFAULT -1,
    new_status int NOT NULL DEFAULT -1
);

INSERT INTO items (id) VALUES ('3e741808-1a69-4ed4-83ca-3cf9832bd080');
INSERT INTO item_status_events (item_id) VALUES ('3e741808-1a69-4ed4-83ca-3cf9832bd080');
```

Test code:
```
import { knex } from "knex";
import { logger } from "./logger";

type ItemStatusEvent = {
  item_id: string;
  old_status: number;
  new_status: number;
  created_at: Date;
};

const db = knex({
  client: "postgresql",
  connection: "connection",
  pool: {
    min: 2,
    max: 10,
  },
});

const itemId = "3e741808-1a69-4ed4-83ca-3cf9832bd080";

function insert(iteration: number) {
  db.transaction(async (tx) => {
    logger.debug(`STARTING CONNECTION ${iteration}`);

    await tx("items").forUpdate().whereIn("id", [itemId]);

    const latest_event = await tx<ItemStatusEvent>("item_status_events")
      .where({ item_id: itemId })
      .orderBy("created_at", "desc")
      .first();

    logger.debug(`LATEST UPDATE ${JSON.stringify(latest_event)}`);

    await tx<ItemStatusEvent>("item_status_events").insert({
      item_id: itemId,
      old_status: latest_event?.new_status,
      new_status: iteration,
    });

    logger.debug(`Finished insertion for iteration=${iteration}`);
  });
}

for (let i = 0; i < 10; i++) {
  insert(i);
}
```

|**0.20.10**|**0.20.11+**|
|---|---|
|![image](https://user-images.githubusercontent.com/4146037/131221953-8c76b526-fd0b-450c-8f47-0d30eaf62cdb.png)|![image](https://user-images.githubusercontent.com/4146037/131221972-c317771b-9df7-43df-8441-832faa10cd36.png)|
|![image](https://user-images.githubusercontent.com/4146037/131221978-fad123d4-6d5e-4ece-a987-8df5df439793.png)|![image](https://user-images.githubusercontent.com/4146037/131221982-dfee2cd9-45d6-4f3d-b3af-04b78d67aabe.png)|

**Comment by MagsMagnoli** [comment] 2021-08-28 14:56
@maximelkin so as you can see above iteration 7 of the issue which starts after 9 was able to read the value of 9 and update to its value of 7 but then was rearranged to being lower than iteration 9

**Comment by maximelkin** [comment] 2021-08-29 04:19
But why

```js
for (let i = 0; i < 10; i++) {
  insert(i);
}
```

and not
```js
(async () => {
for (let i = 0; i < 10; i++) {
  await insert(i);
}
})()
```
Not sure its good idea to be dependent on order of their execution in first case. (This is start of 10 independent tasks, ordered only by start, they could go in other order from any difference in execution time i.e. BEGIN query execution time)

Sorry, probably I'm trying to solve wrong problem, because I can't understand, why this should be explicitly in that way.

**Comment by MagsMagnoli** [comment] 2021-08-29 05:29
@maximelkin in our production system we have separate services issuing requests. each does call await but since they are separate systems in this example its misleading to do it here

**Comment by MagsMagnoli** [comment] 2021-08-30 15:35
@maximelkin for our use case we should be able to get by with switching to clock_timestamp but that indicates that the first log message announcing the start of the transaction is actually later than it "really" started if the timestamps it generates occur earlier. would that maybe have to do with the `db.transaction` statement issuing `begin` before it has a pool connection or some other processing that delays reaching the first log statement?

**Comment by maximelkin** [comment] 2021-08-31 00:42
I can't really get which conditions should order your parallel transactions in correct way. Maybe you should change

```typescript
    const latest_event = await tx<ItemStatusEvent>("item_status_events")
      .where({ item_id: itemId })
      .orderBy("created_at", "desc")
      .first();
```
to also require strictly previous step? (i.e. add filter & check after if any rows selected)

**Comment by maximelkin** [comment] 2021-09-01 01:33
I probably get it, going to recheck why this would happen

**Comment by maximelkin** [comment] 2021-09-01 01:36
So basically, start of transaction A on postgres server happens before start of transaction B, but on applications side transaction A start observed after start of transaction B.

**Comment by elhigu** [comment] 2021-09-26 20:15
I don't see any problem in the original post.... If you launch 10 queries / transactions in parallel, nothing guarantees their execution order.

**Comment by elhigu** [comment] 2021-09-26 20:19
Closing since this doesn't look like a bug, but expected behavior.

**Closed by elhigu** 2021-09-26 20:19 UTC
Labels: transactions, high priority
