### ISSUE TITLE
"Error: aborted" when querying for results not found in database

### ISSUE THREAD

**Issue by NickBeukema** [knex/knex#3841] opened 2020-05-06 01:53 UTC
# Environment

Knex version: 0.21.1
Database + version: Postgres, 11.2
OS: MacOS, Linux for Database (Docker)

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

After upgrading from `0.20.15` to `0.21.1`, any of my queries that would return no results are getting an aborted error, seems like it's dealing with the connection pool.

2. Error message

```
Error: aborted
        at PendingOperation.abort (./project/node_modules/tarn/dist/PendingOperation.js:25:21)
        at./project/node_modules/tarn/dist/Pool.js:203:25
        at Array.map (<anonymous>)
        at ./project/node_modules/tarn/dist/Pool.js:202:53
```

3. Reduced test code, for example in https://npm.runkit.com/knex or if it needs real
   database connection to MySQL or PostgreSQL, then single file example which initializes
   needed data and demonstrates the problem.

Finding it in simple find by ID queries, and also some complex raw ones, like the following:

```
const keys = [1]
const flatKeyTubles = [[45, 'THO', '2020-01-01', '2020-04-01']]
const results = await table.whereRaw(
          `
        ("userId", "symbol", "startDate", "endDate") IN
        ( ${keys.map((k) => "(?, ?, ?, ?)")} )
      `,
          flatKeyTuples
        );
```

**Comment by kibertoad** [comment] 2020-05-06 13:00
@elhigu Could we have broken something in tarn.js update? I think that's the main change in mentioned version change interval.

**Comment by elhigu** [comment] 2020-05-06 13:37
Probably has something to do with it. Need to write reproduction of to our test bench... I would say that it is really strange if this common case is not catched by any of the test suites.

**Comment by mbabauer** [comment] 2020-06-04 17:34
@elhigu Did you ever figure out what was causing this issue?  I am seeing it on an insert from a unit test using sqllite3 in-memory as the DB.  It doesn't give much info other than "Error: aborted".

**Comment by elhigu** [comment] 2020-06-04 17:59
Needs a complete reproduction. Just "querying for results not found in database" probably doesn't cause this since in that case this issue would be flooded with comments. 

Closing until proper reproduction is provided.

**Closed by elhigu** 2020-06-04 17:59 UTC

**Comment by Aposhian** [comment] 2020-06-08 17:03
I got this error when I was accidentally calling knex.destroy() and then performing more queries on that knex object.

**Comment by MarcWeber** [comment] 2020-11-23 14:21
The main issue is that the relation to knex is not clear. Tarn ? What is that ? So a much better error message would be' knex - connection closed' or something like that. So I think a much more descriptive error message could be used.

**Comment by Agilulfo1820** [comment] 2021-07-15 12:54
I have same error with AdonisJs v4, which is using Knex under the hood.

I get this errors in jobs
```
 Error: aborted
api |     at PendingOperation.abort (/srv/app/node_modules/tarn/lib/PendingOperation.js:23:21)
api |     at /srv/app/node_modules/tarn/lib/Pool.js:138:25
api |     at Array.map (<anonymous>)
api |     at /srv/app/node_modules/tarn/lib/Pool.js:137:53
api | From previous event:
api |     at Client_MySQL.acquireConnection (/srv/app/node_modules/knex/lib/client.js:333:33)
api |     at Runner.ensureConnection (/srv/app/node_modules/knex/lib/runner.js:226:24)
api |     at Runner.run (/srv/app/node_modules/knex/lib/runner.js:33:41)
api |     at Builder.Target.then (/srv/app/node_modules/knex/lib/interface.js:23:43)
api |     at runMicrotasks (<anonymous>)
api |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

But this error usually it's not caused by that job but from some other job or connection to db opened elsewhere.
I'm trying to use await `Database.close()` mostly everwhere to prevent this but I still get this issue.

**Comment by jehangir001** [comment] 2022-03-26 18:39
Try this, It solved my issue, need parameter to pass

Not working
finally( knex.destroy());

Working
.finally( x => knex.destroy());

**Comment by jehangir001** [comment] 2022-03-26 18:58
Use this, it solve my problem

 .finally( x => knex.destroy());

**Comment by shadab14meb346** [comment] 2022-05-21 02:46
> I got this error when I was accidentally calling `knex.destroy()` and then performing more queries on that `knex` object. (This was with a MySQL client, not Postgres). Knex version 0.21.1

thanks for pointing this out.
this resolved my issue.
