### ISSUE TITLE
Mysql connection not close issue

### ISSUE THREAD

**Issue by sagar-tts** [knex/knex#4612] opened 2021-08-09 13:49 UTC
Here is code example of serverless and mysql2 with knexjs lib
in the AWS lambda function not close connection after idle time set 1000ms

used libs
- serverless
- Mysql2
- Knexjs v0.95

```
import knex from "knex";
import mysql2 from "mysql2";

if (typeof rdsClient === "undefined") {
  // Connect to the MySQL database
  var rdsClient = knex({
    client: "mysql2",
    connection: {
      host: "localhost",
      port: 3306,
      user: "test-user",
      password: "test-password",
      database: "test-db",
      pool: {
        min: 0,
        max: 1,
        idleTimeoutMillis: 1000,
      }
    }
  });

}

async function fetchUsers() {
    return await rdsClient.select().from('users');
}

fetchUsers();
```
It continuously increase and DB connection and it close around after 10 minuets

Thanks,

**Comment by elhigu** [comment] 2021-08-09 14:42
Please add some code allowing to reproduce the problem. The code above cannot behave like described, since it doesn't even create any connections, since no queries to DB is done.

**Comment by sagar-tts** [comment] 2021-08-10 04:59
Above code used as separate file and import where it needed in the AWS lambda function using serverless.

when request comes to lambda function it will going to create new connection and not close.
I used `idleTimeoutMillis` flag for close connection if more then 1 second open idle time(if not used that connection).

Simple use any lambda function this issue will generate.

Please let me know want more detail.

Thanks,

**Comment by elhigu** [comment] 2021-08-10 08:29
> when request comes to lambda function it will going to create new connection and not close.

The code above does not create any database connections. Knex doesn't create connections until some db queries are made.

**Comment by sagar-tts** [comment] 2021-08-10 09:55
Added simple query at detail.

```
async function fetchUsers() {
    return await rdsClient.select().from('users');
}

fetchUsers();
```

**Comment by elhigu** [comment] 2021-08-10 10:48
Maybe the process is just killed before DB connection is closed, though it is strange if it stays open if process dies. You could add `await rdsClient.destroy()` before ending.

**Comment by sagar-tts** [comment] 2021-08-11 05:20
Above is just one example I have multiple query at many place and don't know or detect queries is running or finish all of them.
So where to add **destroy** method/function.

I have added **tren** pool parameters and function destroyRequest and destroySuccess but all connection are not going to close.

It open 10 connection and close only 6 or 7.

**Comment by elhigu** [comment] 2021-08-11 09:00
Umm... how does AWS lambda know that your function has done its work and its context can be destroyed? You do wait that all the 
queries returns and only after that return from the lambda function?

**Comment by elhigu** [comment] 2021-08-11 09:07
Have you read this one? https://docs.aws.amazon.com/lambda/latest/dg/nodejs-handler.html currently it just sounds that you are not using it correctly. Try to make reduced test case of your code in a way that you can pinpoint where things doesn't work anymore.

Anyways basic principle is that you should do event handler:

```
exports.handler = async function(event) {
  const retVal = await someKnexQueryStuff();
  ... 
  await knex.destroy();
  return retVal;
}
``` 

Closing as this doesn't seem to be knex bug, but usage support.

**Closed by elhigu** 2021-08-11 09:07 UTC

**Comment by sagar-tts** [comment] 2021-08-11 09:11
It seems issue with lambda or serverless not in knexjs.

Thank you for clear this things.

**Comment by sagar-tts** [comment] 2021-08-13 05:00
Will raised issue on AWS support.

You can close this thread.
Thanks for quick response.
