### ISSUE TITLE
Module '"knex"' has no exported member 'Knex'. Did you mean to use 'import Knex from "knex"' instead?

### ISSUE THREAD

**Issue by lancejpollard** [knex/knex#4574] opened 2021-07-16 11:23 UTC
# Environment

Knex version: 0.95.7
Database + version:
OS: Mac

@lorefnon

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

It should allow me to use type definitions in migration files.

2. Error message

```
Module '"knex"' has no exported member 'Knex'. Did you mean to use 'import Knex from "knex"' instead?
```

3. Reduced test code

```js
import { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {

}
```

Error when running migration.

**Comment by kibertoad** [comment] 2021-07-16 12:19
What TypeScript version? Also are you sure there are no conflicting knex versions? it is common to have separate global knex for cli operations.

**Comment by lancejpollard** [comment] 2021-07-17 00:11
Hmm, it's possible I had a global knex

**Comment by kibertoad** [comment] 2021-07-25 17:47
@lancejpollard Did you manage to resolve your issue?

**Comment by Naragod** [comment] 2021-07-26 20:34
I am facing the same issue.

Typescript version: 4.3.5
knex version: 0.95.7
pg: 8.6.0

**Comment by ShivamJoker** [comment] 2021-08-14 12:11
I am also getting this typescript error

**Comment by kibertoad** [comment] 2021-08-23 12:34
@Naragod @ShivamJoker Could you please share your code? Also can you check that there is no older version of knex installed globally?

**Comment by ShivamJoker** [comment] 2021-08-23 16:51
Guys you need explicitly tell the latest library version, IDK for some reason it is downloading the old version of library.
```sh
yarn add knex@0.95.10
```

Also make sure the typescript version is latest too.

**Comment by elhigu** [comment] 2021-09-26 19:44
@kibertoad was this fixed?

**Comment by kibertoad** [comment] 2021-09-26 19:48
@elhigu It's not a bug, it's migration guide being ignored.

**Comment by elhigu** [comment] 2021-09-26 21:41
mm ok, so closing this 👍

**Closed by elhigu** 2021-09-26 21:41 UTC
