### ISSUE TITLE
Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?

### ISSUE THREAD

**Issue by azebuji** [knex/knex#4486] opened 2021-05-13 22:41 UTC
# Environment
I'm having the problem with pool full, but i'm using the commit and rollback and the auto-commit method, none of them have effects.

`return await knex.transaction(async (trx) => { return 'teste' }) `

"inside of this code there are some rows, but I removed it for better comprehension".

I tested a lot of times, and the pool is getting full and don't commiting the transactions, if I save the project when It running the commit occurs, I really don't know what happens.

I'm using:
node version 16.0.0
"pg": "^8.6.0"
"ts-node": "^9.1.1",
"ts-node-dev": "^1.1.6",
"knex": "0.21.17",

and I tried another versions of node, pg, knex and ts-node, none of them have solved my problem.

**This is my pool.** 
```
Pool {
  destroyed: false,
  emitter: EventEmitter {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined
  },
  creator: [AsyncFunction: create],
  destroyer: [Function: destroy],
  validate: [Function: validate],
  log: [Function],
  acquireTimeoutMillis: 60000,
  createTimeoutMillis: 30000,
  destroyTimeoutMillis: 5000,
  idleTimeoutMillis: 30000,
  reapIntervalMillis: 1000,
  createRetryIntervalMillis: 200,
  propagateCreateError: true,
  min: 0,
  max: 14,
  used: [
    Resource {
      resource: [Client],
      timestamp: 1620945463143,
      deferred: [Object]
    },
    Resource {
      resource: [Client],
      timestamp: 1620945463181,
      deferred: [Object]
    },
    Resource {
      resource: [Client],
      timestamp: 1620945463479,
      deferred: [Object]
    },
    Resource {
      resource: [Client],
      timestamp: 1620945463725,
      deferred: [Object]
    },
    Resource {
      resource: [Client],
      timestamp: 1620945463795,
      deferred: [Object]
    },
    Resource {
      resource: [Client],
      timestamp: 1620945463934,
      deferred: [Object]
    },
    Resource {
      resource: [Client],
      timestamp: 1620945464028,
      deferred: [Object]
    },
    Resource {
      resource: [Client],
      timestamp: 1620945464235,
      deferred: [Object]
    },
    Resource {
      resource: [Client],
      timestamp: 1620945464525,
      deferred: [Object]
    },
    Resource {
      resource: [Client],
      timestamp: 1620945464640,
      deferred: [Object]
    },
    Resource {
      resource: [Client],
      timestamp: 1620945464831,
      deferred: [Object]
    },
    Resource {
      resource: [Client],
      timestamp: 1620945464926,
      deferred: [Object]
    },
    Resource {
      resource: [Client],
      timestamp: 1620945465559,
      deferred: [Object]
    }
  ],
  free: [
    Resource {
      resource: [Client],
      timestamp: 1620945465629,
      deferred: [Object]
    }
  ],
  pendingCreates: [],
  pendingAcquires: [],
  pendingDestroys: [],
  pendingValidations: [],
  interval: Timeout {
    _idleTimeout: 1000,
    _idlePrev: [TimersList],
    _idleNext: [TimersList],
    _idleStart: 4774,
    _onTimeout: [Function],
    _timerArgs: undefined,
    _repeat: 1000,
    _destroyed: false,
    [Symbol(refed)]: true,
    [Symbol(asyncId)]: 770,
    [Symbol(triggerId)]: 0
  },
  eventId: 41
}
Error: Transaction rejected with non-error: undefined
    at D:\Api-inPg\node_modules\knex\lib\transaction.js:139:21
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

**Comment by elhigu** [comment] 2021-05-17 06:31
Can you provide the complete test code, how you are getting that error just by running that row of code?

```
await knex.transaction(async (trx) => { return 'teste' })
```

If you are just looping over that line, you should not be getting that error.

**Comment by azebuji** [comment] 2021-05-17 15:53
I'm having this erros in all my routes that have BD manipulation, when I login so many times in the same connection,
When I delete or save something in the system with the same transaction "trx".

this is one of my routes, this route is recover a password.

`export async function putSend(email: string) {


  try {

    const trx = await knex.transaction();

    return await trx<Login>('login').select('id_login').where({ email }).first().pluck('id_login').then(async ([id_login]) => {


      return await trx<RecoverPassword>('recover_password').select('id_recover_password').where('rp_id_login', id_login ? id_login : 0).then(async (founded) => {
        if (founded.length) {
          await trx<RecoverPassword>('recover_password').del().where({ rp_id_login: id_login });
        }
        let hash = await bcrypt.hash(moment().format('DD/MM/YYYY HH:mm') + email, 10);
        return await trx<RecoverPassword>('recover_password').insert({ hash, dt_created: new Date(), rp_id_login: id_login }).then(async () => {
          return id_login ? { email, hash } : 'empty';
        })
      })
    }).then(async data => {
      await trx.commit();
     return data ?data : 'empty'
    }).catch(async error => {
      await trx.rollback();
      return error;
    })




  } catch (error) {
    console.log(error)
    return error;
  }
}`


This is my connection file

`import knex from 'knex';
import {env} from '../config/env/env';
let { host, user, password, database, client } = env.dataConfig.POSTGRES;

const connection = knex({
  client: client,
  connection: {
    host: host,
    user: user,
    password: password,
    database: database,
  },
  pool: env.pool,
  
  
});



export default connection;`


This is my knexfile

`import {env} from './src/config/env/env';
let {client, user, database, password, host, port} = env.dataConfig.POSTGRES;
import path from 'path';

module.exports = {
  client: client,
  connection: {
    host: host,
    user: user,
    password: password,
    database: database,
    port: port,
  },
  migrations: {
    directory: path.resolve(__dirname, 'src', 'database', 'migrations'),
  }, 
  seeds: {
    directory: path.resolve(__dirname, 'src', 'database', 'seeds'),
  },
};`

**Comment by elhigu** [comment] 2021-05-17 16:25
You need to isolate your failing code. This is still not reproducable. Closing as doesn't look like knex bug / cannot reproduce.

May be reopened if minimal reproduction is provided and there is reason to suspect that this is indeed a bug in knex.

See https://github.com/knex/knex/blob/master/CONTRIBUTING.md#what-is-minimal-code-to-reproduce-bug-and-why-i-have-to-provide-that-when-i-can-just-tell-whats-the-problem-is

**Closed by elhigu** 2021-05-17 16:25 UTC
