### ISSUE TITLE
Subquery not working with withSchema

### ISSUE THREAD

**Issue by dizlexik** [knex/knex#1368] opened 2016-04-26 21:30 UTC
I ran into this issue today and it's blocking me for now :/

This produces the expected query:
`knex.select(1).from(function() { this.select(1).from('mytable') })`
-> `select 1 from (select 1 from [mytable])`

This does not:
`knex.withSchema('myschema').select(1).from(function() { this.select(1).from('mytable') })`
-> `select 1 from [myschema].[function () { this].[select(1)].[from('mytable'); }]`

**Comment by igor-savin-ht** [comment] 2017-11-28 13:09
@elhigu Any way to contribute to this issue? Would e. g. test that reproduces the issue help?

**Comment by elhigu** [comment] 2017-11-29 17:58
@igor-savin-ht PR with test + fix would be really helpful. I don't have fixing this issue in my todo list.

**Comment by devourment77** [comment] 2018-05-22 19:54
I hit this issue today.  It looks like the schema is prepended to the subquery (EX: `<schema>.select`)

**Comment by kibertoad** [comment] 2021-03-03 19:58
Released in 0.95.0, please reopen if this still does not work for you.

**Closed by kibertoad** 2021-03-03 19:58 UTC
Labels: bug
