### ISSUE TITLE
Knex is unable to insert an array [] into a JSON column in MySQL (reproducable) 

### ISSUE THREAD

**Issue by dsomel21** [knex/knex#4021] opened 2020-09-06 22:10 UTC
# Environment

Knex version: **0.21.5-next2**
Database + version: **MySQL  5.7.29**
OS: **MacOS Cataline 10.15.6**

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do

I am inserting data that includes strings, FKID, integers and **arrays.** Here is an example of what I am trying to insert: 

```json
{
  line_number: 1,
  content_unicode: "ਤੀਨੋ ਲੋਕ ਬਰ ਦਾਨੀ ਤੀਨੋ ਜਾਚੈ ਮਹਾਰਾਨੀ ਤੀਨੋ ਤਾਪ ਹਾਨੀ ਆਦਿ ਤੀਨੋ ਗੁਨ ਮੰਡਿਕਾ ।",
  content_gs: "qIno lok br dwnI qIno jwcY mhwrwnI qIno qwp hwnI Awid qIno gun mMifkw [",
  content_transliteration_english: "teeno lok bar dhaanee teeno jaachai mahaaraanee teeno taap haanee aadh teeno gun ma(n)ddikaa |",
  first_letters: "ਤਲਬਦਤਜਮਤਤਹਆਤਗਮ",
  thamkis: [3, 9],
  vishraams: [6],
  chhand_id: 2,
  chhand_type_id: 2,
  chapter_id: 1,
  pauri_id: 12,
}
```

This is the actual code for, but it is working smooth: 

```javascript
Promise.all(
    req.body.pauri.map((tuk) => {
      return db('tuks').insert({
        ...tuk,
        chhand_id: chhand.id,
        chhand_type_id: chhand.chhand_type_id,
        chapter_id: chhand.chapter_id,
        pauri_id: pauri.id,
        // vishraams: null, /* NOTE: Insert works when this is unncommented */
        // thamkis: null, /* NOTE: Insert works when this is unncommented */
      });
    })
  )
```

2. Error message

**`ER_WRONG_VALUE_COUNT_ON_ROW`**

After further investigation, I looked at the `.sql` error message: Here is an image:

<img width="1354" alt="Knex - Situation with inserting arrays" src="https://user-images.githubusercontent.com/17516559/92336170-c37ae700-f06b-11ea-8f16-b9b22af508d1.png">

**Proof:**
So, I took that query into POPSQL and sure enough it failed. You can also see the corrected version.
<img width="1420" alt="Knex insert array query fix" src="https://user-images.githubusercontent.com/17516559/92336204-3be1a800-f06c-11ea-8d67-9e5d9aafe919.png">

**Comment by dsomel21** [comment] 2020-09-06 22:19
For now, if you do `JSON.stringify(array)` it is a good temp fix (for my case). If anyone else is reading, you can try and let me know.

**Comment by elhigu** [comment] 2020-09-07 06:13
Putting reproducible to title doesn't make it magically reproducible. In contributing.md there is text how to create minimal reproduction code for an issue.

Closing as this doesn't look like a knex bug.

**Closed by elhigu** 2020-09-07 06:13 UTC

**Comment by dsomel21** [comment] 2020-09-07 17:33
Sorry, I've removed the "reproducible" tag since it doesn't meet those standards.  

It's a bit uncalled for to just close it off and say _this dOeSn't look like a knex bug._ 

Maybe it isn't, but I obviously can't see it (hence, why I went through the effort to make this issue).

**Comment by elhigu** [comment] 2020-09-08 04:52
> It's a bit uncalled for to just close it off and say this dOeSn't look like a knex bug.

If we would leave all the issues open that does not have clear minimal reproduction included  
(https://github.com/knex/knex/blob/master/CONTRIBUTING.md#what-is-minimal-code-to-reproduce-bug-and-why-i-have-to-provide-that-when-i-can-just-tell-whats-the-problem-is) and looks more like an user error, the issue tracker would have hundreds or even thousands of unresolved issues which for nobody could do anything.

Also creating that single file runnable reproduction showing exactly what is the observed behaviour and what would be baseline for the effort that people should put to reporting bugs. It helps them to actually pinpoint their problem and us to directly tell from code if it is expected behaviour or not.

Of course this issue can be reopened if minimal reproduction is provided that shows that there actually is a bug in knex. 

Usually in these cases when dev is creating the minimal reproduction he/she will actually find the real problem in their code in the process.

**Comment by aleclarson** [comment] 2022-04-15 00:20
I'm also seeing this issue.

Does knex have enough information to know when I'm inserting a JS array into a `JSON` column? It's my understanding that the current behavior (spreading the array into multiple column values, as seen in the OP's screenshots) is not the intended behavior.
